### ISSUE TITLE
offitial version?

### ISSUE THREAD

**Issue by huangfuyb** [kyoyachuan/metafscil#1]
Hi, nice job! It's a reproductive version or offitial version of [this paper](https://openaccess.thecvf.com/content/CVPR2022/html/Chi_MetaFSCIL_A_Meta-Learning_Approach_for_Few-Shot_Class_Incremental_Learning_CVPR_2022_paper.html)?

**Comment by kyoyachuan** [comment]
Hi, it's a reproductive version. Thanks for your attention~
